org: elicervantess
service: api-productos

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  role: arn:aws:iam::633777173661:role/LabRole
  environment:
    DYNAMODB_TABLE_PRODUCTS: ${sls:stage}-t-products
    JWT_SECRET: ${env:JWT_SECRET}

plugins:
  - serverless-dotenv-plugin

functions:
  createProduct:
    handler: src/createProduct.handler
    events:
      - http:
          path: productos/create
          method: post

  getProduct:
    handler: src/getProduct.handler
    events:
      - http:
          path: productos/get/{productId}
          method: get

  listProducts:
    handler: src/listProducts.handler
    events:
      - http:
          path: productos/list
          method: get

  updateProduct:
    handler: src/updateProduct.handler
    events:
      - http:
          path: productos/update/{productId}
          method: put

  deleteProduct:
    handler: src/deleteProduct.handler
    events:
      - http:
          path: productos/delete/{productId}
          method: delete

resources:
  Resources:
    ProductsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${sls:stage}-t-products
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: productId
            AttributeType: S
          - AttributeName: globalProductId   
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: productId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: GlobalProductIndex  
            KeySchema:
              - AttributeName: globalProductId
                KeyType: HASH
            Projection:
              ProjectionType: ALL

package:
  exclude:
    - __pycache__/**
    - tests/**
    - venv/**
