org: elicervantess
service: api-usuarios

provider:
  name: aws
  runtime: python3.12
  region: us-east-1
  environment:
    JWT_SECRET: ${env:JWT_SECRET}
    TOKEN_EXPIRY: ${env:TOKEN_EXPIRY}
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - dynamodb:*
          Resource:
          - "arn:aws:dynamodb:${self:provider.region}:*:table/${sls:stage}-t_users"

plugins:
  - serverless-dotenv-plugin
  - serverless-python-requirements
  - serverless-offline

custom:
  pythonRequirements:
    dockerizePip: true
    fileName: requirements.txt

functions:
  create_user:
    handler: src.create_user.lambda_handler
    events:
      - http:
          path: users/register
          method: post

  login_user:
    handler: src.login_user.lambda_handler
    events:
      - http:
          path: users/login
          method: post
          
  validate_token:
    handler: src.validate_token.lambda_handler
    events:
      - http:
          path: users/validate-token
          method: post

resources:
  Resources:
    UsersTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: ${sls:stage}-t_users
        AttributeDefinitions:
          - AttributeName: "tenantId"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "tenantId"
            KeyType: "HASH"
        BillingMode: PAY_PER_REQUEST

package:
  exclude:
    - __pycache__/**
    - venv/**
