org: elicervantess
service: api-compras

provider:
  name: aws
  runtime: python3.12
  region: us-east-1
  role: arn:aws:iam::633777173661:role/LabRole
  environment:
    PYTHONPATH: src/
    JWT_SECRET: ${env:JWT_SECRET}
    DYNAMODB_TABLE_PURCHASES: ${sls:stage}-t-purchases

plugins:
  - serverless-dotenv-plugin
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    fileName: requirements.txt

functions:
  list_purchases:
    handler: src.list_purchases.lambda_handler
    events:
      - http:
          path: purchases
          method: get

  register_purchase:
    handler: src.register_purchase.lambda_handler
    events:
      - http:
          path: purchases
          method: post

resources:
  Resources:
    PurchasesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.stage}-t-purchases
        AttributeDefinitions:
          - AttributeName: "tenant_id"
            AttributeType: "S"
          - AttributeName: "purchase_id"
            AttributeType: "S"
          - AttributeName: "purchaseDate"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "tenant_id"
            KeyType: "HASH"
          - AttributeName: "purchase_id"
            KeyType: "RANGE"
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: "ComprasPorFechaIndex"
            KeySchema:
              - AttributeName: "tenant_id"
                KeyType: "HASH"
              - AttributeName: "purchaseDate"
                KeyType: "RANGE"
            Projection:
              ProjectionType: "ALL"

package:
  exclude:
    - __pycache__/**
    - venv/**
