openapi: 3.0.0
info:
  title: API Compras
  version: 1.0.0
  description: API para registrar compras multi-tenant y listar compras del usuario.

paths:
  /purchases:
    post:
      summary: Registrar nueva compra
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId: { type: string }
                items:
                  type: array
                  items:
                    type: object
                    properties:
                      productId: { type: string }
                      quantity: { type: integer }
      responses:
        '200':
          description: Compra registrada

    get:
      summary: Listar compras del usuario
      parameters:
        - in: query
          name: userId
          required: true
          schema: { type: string }
      responses:
        '200':
          description: Lista de compras del usuario
